### PR TITLE
add more comment for new to git

### PR DESCRIPTION
**Pull request by LuckyPigeon**

### CODE REVIEW

**Comment by LuckyPigeon** [comment]
Sorry for I left env file in PyBeacon.

**Comment by LuckyPigeon** [comment]
@PrabhanshuAttri can you review this PR, thanks

**Comment by LuckyPigeon** [comment]
@PrabhanshuAttri Could you review this PR and merge is to master? thanks

**Comment by PrabhanshuAttri** [comment]
@LuckyPigeon I am closing this PR as there are many env files. Let me know if this PR is different from #67, I will reopen it.

**Pull request closed without merging**
